#!/usr/bin/perl
my $status = 1;

sub on_user_command {
  my($term, $command) = @_;

  if ($command eq "notify-toggle") {
    $status = 1 - $status;

    if ($status eq 1) {
        system("notify-send", ("Beep in terminal"))
    } else {
        system("notify-send", ("Beep in terminal"))
    }
  }
}

sub on_osc_seq_perl {
  my ($term, $osc, $resp) = @_;

  if ($status eq 0) {
      return;
  }

  if ($osc =~ /^notify;(\S+);(.*)$/) {
    system("notify-send", ($1, $2));
  }
}
