image: opensuse:42.1
test:
  stage: test
  script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
    - zypper -n in ruby
    - gem install rspec
    - rspec .
