image: xack/opensuse
test:
  stage: test
  script:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
    - gem install rspec
    - rspec.ruby2.1 -f doc .
